version: 1.0.{build}

build_script:

- ps: .\build.ps1

install:
- cmd: nuget install redis-64 -excludeversion
- cmd: redis-64\tools\redis-server.exe --service-install
- cmd: redis-64\tools\redis-server.exe --service-start

before_build:
- cmd: regsvr32 /s /n /i:user .\tools\Cake\x64\OpenCover.Profiler.dll
