version: 1.0.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: HnIQ1tqZF5BksvfN+tPVUujSMa/PgR/gL3mLXfL88bpTm25MlQirtzbohLX+FVe5

build_script:

- ps: .\build.ps1

install:
- cmd: nuget install redis-64 -excludeversion
- cmd: redis-64\tools\redis-server.exe --service-install
- cmd: redis-64\tools\redis-server.exe --service-start

after_build:
- cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover result.xml
